CREATE TABLE dokumen_file (
    id INT PRIMARY KEY AUTO_INCREMENT,
    dokumen_id INT NOT NULL,
    file TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);