CREATE TABLE dokumen (
    id INT PRIMARY KEY AUTO_INCREMENT,
    no_dokumen VARCHAR(200) NOT NULL,
    id_kategori_dokumen VARCHAR(50) NOT NULL,
    judul VARCHAR(200) NOT NULL,
    deskripsi TEXT NULL,
    id_pengguna INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);