CREATE TABLE dokumen_kategori (
    id INT PRIMARY KEY AUTO_INCREMENT,
    kode VARCHAR(255) NOT NULL,
    kategori TEXT NOT NULL,
    keterangan TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);