CREATE TABLE jenis_pengguna (
    id INT PRIMARY KEY AUTO_INCREMENT,
    jenis_pengguna VARCHAR(255) NOT NULL,
    keterangan text NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

